### ISSUE TITLE
Memory leak when downloading files

### ISSUE THREAD

**Issue by axelson** [appcues/mojito#76]
Simply downloading some large files (tested with a 17MB file) is enough to cause the Beam's memory to grow and not be reclaimed after a garbage collection:

```
iex> task = Task.async(fn -> Mojito.get(url, [auth]); :ok end); Task.await(task)
:ok 
iex> task = Task.async(fn -> Mojito.get(url, [auth]); :ok end); Task.await(task)
:ok 
iex> task = Task.async(fn -> Mojito.get(url, [auth]); :ok end); Task.await(task)
:ok 
```

This may be caused by how poolboy copies data between processes.

Originally reported on the ElixirForum:
https://elixirforum.com/t/memory-leak-binaries-that-only-recon-bin-leak-1-helps-with/35804

**Comment by gamache** [comment]
Thanks for the report. This is isn't what I would call a memory leak though; it's bounded to the size of the pool.

It seems like the operational issue is that a Poolboy pool of idle Mojito workers consumes as much memory as a pool of busy workers, because binary memory is GCed from the idle worker processes in a deferred fashion.

If this condition is triggering out-of-memory errors on constrained systems, it indicates to me that the pool is too large -- the system couldn't use all those connections at the same time anyway, even if it needed to.

However, I'll investigate and see if there's a performant way to force a GC on workers as they are checked back into the pool.

(cc: @hubertlepicki)

**Comment by gamache** [comment]
Adding a strategic `:erlang.garbage_collect(worker)` when a request completes makes a noticeable impact here; my test system that idled around 400MB of binary memory before this change is now idling around 150MB. I'll work this into a PR. Thanks again for the report @axelson!
